class_name GameConfig
extends RefCounted

const TICKS_PER_SECOND := 60
const MAX_HP := 1000
const BUILD_BUDGET := 500
const MAX_MOVES := 4
const MAX_EFFECTS := 2
const MIN_ATTACK_POWER := 25
const MAX_DAMAGE_PER_HIT := 500
const CHARGE_POOL := 600
const MIN_CHARGES := 1
const MAX_CHARGES := 8
const INPUT_BUFFER_TICKS := 6
const CONTROL_TRIGGER_TICKS := 12
const CONTROL_IMMUNITY_TICKS := 90
const BASIC_ATTACK_DAMAGE := 20
const SHIELD_ACTIVE_TICKS := 6
const SHIELD_WHIFF_RECOVERY_TICKS := 12
const SHIELD_COOLDOWN_TICKS := 3 * TICKS_PER_SECOND
const SHIELD_REQUIRED_CONTACTS := 2
const ARENA_HALF_WIDTH := 1000
const MIN_FIGHTER_SPACING := 40
const CLOSE_RANGE := 100
const LONG_RANGE := 500
const START_DISTANCE_FROM_CENTER := 250
const UPPERCUT_AIRBORNE_TICKS := 45
const MAX_AIRBORNE_COMBO_HITS := 3
const STAGGER_PUSH_DISTANCE := 60
